# Generated by Django 4.0.4 on 2022-04-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created'], 'verbose_name': 'Новости', 'verbose_name_plural': 'Новость'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Резюме', 'verbose_name_plural': 'Резюме'},
        ),
        migrations.AlterModelOptions(
            name='vine',
            options={'ordering': ['-created'], 'verbose_name': 'О Винах', 'verbose_name_plural': 'О Вине'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='type_date_menu',
            field=models.CharField(choices=[('main_menu', 'основное меню'), ('lunch_menu', 'обеденное меню недели')], max_length=51, verbose_name='Типы Меню'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='type_menu',
            field=models.CharField(choices=[('Appetizers_salads', 'Закуски и салаты'), ('Breakfasts', 'Завтраки'), ('Bread', 'Хлеб'), ('Dessert', 'Десерт'), ('Drinks', 'Напитки'), ('Hot_meals', 'Горячие блюда'), ('Snacks', 'Закуски'), ('Salads', 'Салаты'), ('Burgers', 'Бургеры'), ('Steaks', 'Стейки'), ('Fish', 'Рыба'), ('Soups', 'Супы'), ('Garnishes', 'Гарниры'), ('Sauces', 'Соусы'), ('Desserts', 'Десерты'), ('Freshies', 'Фреши'), ('Drinks', 'Напитки'), ('Coffee', 'Кофе (Honduras San Marcos, Kitchen Coffee Roasters)')], max_length=51, verbose_name='Виды Блюда'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Описание фото'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='email',
            field=models.CharField(max_length=30, verbose_name='Email'),
        ),
    ]
